### ISSUE TITLE
[FAQ] Why AWK has only associative arrays...

### ISSUE THREAD

**Issue by drawkula** [khwerz/Awk-Batteries#1]
Stuff for a future FAQ:

[[ University of Nottingham] Computer Science - Brian Kernighan on successful language design](https://www.youtube.com/watch?v=Sg4U4r_AgJU&t=1178)
[[Computerphile] Essentials: Brian Kernighan on Associative Arrays - Computerphile](https://www.youtube.com/watch?v=qTZJLJ3Gm6Q)

**Comment by Nomarian** [comment]
Added a FAQ Section to the wiki, though I would like it better to have a website somewhere else instead.


Strange though, I thought wiki's were editable by everyone. if you find out how I'll add you.

**Comment by drawkula** [comment]
Looks like I can add stuff to the existing page...  \o/

**Comment by Nomarian** [comment]
:)


I think I've added every single thing I have bookmarked.


Next up, maybe tutorials? merge everything that's in the awk wiki archive?
